name: airly_monitor
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  #Flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #General
  auto_route: ^5.0.2
  device_info_plus: ^8.0.0
  extended_image: ^6.3.2
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  package_info_plus: ^3.0.2
  share_plus: ^6.3.0

  #Auth
  flutter_appauth: ^4.2.1

  #Geolocation
  geolocator: ^9.0.2
  
  #Networking
  connectivity_plus: ^3.0.2
  dio: ^4.0.6
  retrofit: ^3.3.1

  #State managment
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

  #Code managment
  get_it: ^7.2.0
  injectable: ^2.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  #Storage
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^6.0.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3
  retrofit_generator: ^4.2.0
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  freezed: ^2.2.1
  injectable_generator: ^2.0.1
  json_serializable: ^6.5.4

flutter:  
  generate: true